apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  labels:
    team: product
    version: "1.0"
    environment: development
  annotations:
    description: Ini adalah aplikasi yang dibuat oleh Tim Product
    other: Some text...
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80