apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: web
    version: 1.0.0
    description: this-pod-with-label
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80